topics:
  - react
  - vite
  - typescript
  - zustand
  - tailwindcss
  - react-hooks
  - react-template
  - starter-kit
  - boilerplate
  - frontend
  - web-development
  - javascript
  - modern-javascript
  - react18
  - state-management
  - docker
  - eslint
  - prettier
  - husky
  - testing
  - vitest
  - react-testing-library
